apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    dadafoundry.io/image-grafana: grafana:latest
    dadafoundry.io/imageorisshow: ""
    dadafoundry.io/imageorpublic: "true"
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 0
  selector:
    app: grafana
    deploymentconfig: grafana
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: grafana
        deploymentconfig: grafana
    spec:
      containers:
      - image: registry.dataos.io/wangydtest/grafana:dfplus
        imagePullPolicy: Always
        name: grafana
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - grafana
      from:
        kind: ImageStreamTag
        name: grafana:latest
        namespace: openshift-infra
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
